---
title: "p8105_hw6_qz2527"
author: "kindle zhang"
date: "2023-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Problem 1

```{r q1_data_cleaning}
homicide_df = 
  read_csv("./data_file/homicide-data.csv",
           na = c("", "NA", "Unknown")) |> 
  janitor::clean_names() |> 
  mutate(
    city_state = str_c(city , ", ", state),
    # or we can use
    # city_state = str_c(city ,state, sep = ", ")
    victim_age = as.numeric(victim_age),
    resolution = as.numeric(disposition == "Closed by arrest"),
    # or we can use
    #   resolution = case_when(
    #     disposition == "Closed without arrest" ~ 0,
    #     disposition == "Open/No arrest"        ~ 0,
    #     disposition == "Closed by arrest"      ~ 1)
    # ) 
  ) |> 
  filter(victim_race %in% c("White", "Black")) |> 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) |> 
  select(city_state, resolution, victim_age, victim_sex, victim_race)
```

```{r q1_glm_baltimore}
baltomore_glm = 
  homicide_df |> 
  filter(city_state == "Baltimore, MD") |>
  glm(resolution ~ victim_age + victim_sex + victim_race, family = binomial(), data = _)

baltomore_glm |> 
  broom::tidy() |> 
  mutate(
    OR = exp(estimate),
    OR_CI_upper = exp(estimate + 1.96 * std.error),
    OR_CI_lower = exp(estimate - 1.96 * std.error)
  ) |> 
  filter(term == "victim_sexMale") |> 
  select(OR, OR_CI_lower, OR_CI_upper) |>
  knitr::kable(digits = 3)
```

```{r q1_glm_all_cities}
model_results = 
  homicide_df |> 
  nest(data = -city_state) |> 
  mutate(
    models = map(data, \(df) glm(resolution ~ victim_age + victim_sex + victim_race, family = binomial(), data = df)),
    tidy_models = map(models, broom::tidy)
  ) |> 
  select(-data, -models) |> 
  unnest(cols = tidy_models) |> 
  mutate(
    OR = exp(estimate),
    OR_CI_upper = exp(estimate + 1.96 * std.error),
    OR_CI_lower = exp(estimate - 1.96 * std.error)
  ) |> 
  filter(term == "victim_sexMale") |> 
  select(city_state, OR, OR_CI_lower, OR_CI_upper)

model_results |>
  slice(1:5) |>
  knitr::kable(digits = 3)
```

```{r}
model_results |>
  mutate(city_state = fct_reorder(city_state, OR)) |>
  ## like reorder
  ggplot(aes(x = city_state, y = OR)) + geom_point() +
  geom_errorbar(aes(ymin = OR_CI_lower, ymax = OR_CI_upper)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

# Problem 2

first, I import the data and tidy it

```{r import_the_data}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


```{r}

```


